### ISSUE TITLE
Bug Report: findTag t/TagName

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [AY2021S2-CS2103T-T13-2/tp#139]
Typing the above into GUI command line results in an IllegalArgumentException that does not display any message on GUI

**Comment by umergta** [comment]
think its been caused here:

![Screenshot 2021-03-31 at 11 08 44 PM](https://user-images.githubusercontent.com/47556379/113167228-191c1880-9276-11eb-9859-dfc5942adb01.png)

the checkArgument in the constructor of the Tag

**Comment by AiwassPrime** [comment]
In addition, findTag &*(, will also throw exception but never catch
