### ISSUE TITLE
bug report: Issues with jar file

### ISSUE THREAD

**Issue by umergta** [AY2021S2-CS2103T-T13-2/tp#140]
I tried using the jar file in the build/libs of our project but it seems that its the old version? and the UI seems to be the old one?
command used: **java -jar modulebook.jar**

![Screenshot 2021-03-31 at 11 00 27 PM](https://user-images.githubusercontent.com/47556379/113166189-1bca3e00-9275-11eb-9977-cafcbb03f216.png)

**Comment by yhtMinceraft1010X** [comment]
I just swapped out the modulebook.jar file.

I think what happened was the build process was done on a branch that was not updated. Remember to pull the team master branch into your local repos and forks.

**Comment by umergta** [comment]
ok thanks @yhtMinceraft1010X 👍🏼
